"""
Central Prometheus metrics registry for the social trading system.

All services import from this module — each process registers its metrics
once at startup. The HTTP /metrics endpoint is exposed on port 8000 per
service (Prometheus scrapes each container individually).

Design reference: docs/design/13-monitoring-observability.md

Usage:
    from social_trading.monitoring.metrics import (
        start_metrics_server,
        POSTS_INGESTED, SIGNALS_GENERATED, ...
    )
    start_metrics_server(port=8000)

    # In hot path:
    POSTS_INGESTED.labels(source="twitter", ticker="AAPL").inc()
"""
from __future__ import annotations

import logging

from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
    start_http_server,
)

logger = logging.getLogger(__name__)

# ── Ingestion metrics ─────────────────────────────────────────────────────────

POSTS_INGESTED = Counter(
    "posts_ingested_total",
    "Social media posts ingested from any source",
    ["source", "ticker"],
)

POSTS_FILTERED = Counter(
    "posts_filtered_total",
    "Posts dropped before NLP (bots, duplicates, neutral noise)",
    ["reason"],   # "bot", "duplicate", "no_ticker", "neutral"
)

SPIKE_DETECTED = Counter(
    "spike_detected_total",
    "Volume spikes detected (triggers Tier-2 Twitter pull)",
    ["ticker"],
)

INGEST_ERRORS = Counter(
    "ingest_errors_total",
    "Errors in data source polling/streaming",
    ["source", "error_type"],
)

# ── NLP metrics ───────────────────────────────────────────────────────────────

POSTS_CLASSIFIED = Counter(
    "posts_classified_total",
    "Posts that completed full NLP classification",
    ["model", "label"],   # model: vader|finbert|stocktwits_native; label: positive|negative|neutral
)

SENTIMENT_LATENCY = Histogram(
    "sentiment_latency_ms",
    "End-to-end NLP pipeline latency per post (ms)",
    buckets=[10, 25, 50, 100, 200, 500, 1000, 2000],
)

NLP_BATCH_SIZE = Histogram(
    "nlp_batch_size",
    "Number of posts in each FinBERT batch",
    buckets=[1, 2, 4, 8, 16, 32],
)

NLP_ERRORS = Counter(
    "nlp_errors_total",
    "Errors in NLP pipeline processing",
    ["stage"],   # "bot_filter", "ticker_extract", "vader", "finbert"
)

# ── Signal metrics ────────────────────────────────────────────────────────────

SIGNALS_GENERATED = Counter(
    "signals_generated_total",
    "Trading signals generated by signal service",
    ["ticker", "direction"],
)

SIGNAL_QUALITY = Histogram(
    "signal_quality_score",
    "Distribution of signal quality scores (0–1)",
    buckets=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
)

ACTIVE_TICKERS = Gauge(
    "active_tickers_total",
    "Number of tickers currently in the active watchlist",
)

SENTIMENT_SCORE = Gauge(
    "ticker_sentiment_score",
    "Latest aggregated sentiment score per ticker",
    ["ticker"],
)

VOLUME_ZSCORE = Gauge(
    "ticker_volume_zscore",
    "Latest mention volume Z-score per ticker",
    ["ticker"],
)

# ── Risk metrics ──────────────────────────────────────────────────────────────

SIGNALS_APPROVED = Counter(
    "signals_approved_total",
    "Signals approved by risk service",
    ["ticker", "direction"],
)

SIGNALS_REJECTED = Counter(
    "signals_rejected_total",
    "Signals rejected by risk service",
    ["reason"],   # "circuit_breaker", "liquidity", "sizer", "adv_pct"
)

CIRCUIT_BREAKER_STATE = Gauge(
    "circuit_breaker_state",
    "Current circuit breaker state (0=NORMAL, 1=REDUCED_50, 2=DAILY_HALT, 3=FULL_HALT)",
)

CIRCUIT_BREAKER_TRANSITIONS = Counter(
    "circuit_breaker_transitions_total",
    "Number of circuit breaker state transitions",
    ["from_state", "to_state"],
)

# ── Execution metrics ─────────────────────────────────────────────────────────

ORDERS_PLACED = Counter(
    "orders_total",
    "Orders submitted to execution engine",
    ["ticker", "status"],  # status: filled|rejected
)

POSITIONS_CLOSED = Counter(
    "positions_closed_total",
    "Positions closed (any reason)",
    ["reason"],  # TIME_STOP|STOP_LOSS|TAKE_PROFIT|TRAILING_STOP|SENTIMENT_REVERSAL|...
)

POSITION_PNL = Gauge(
    "position_unrealized_pnl",
    "Current unrealized P&L per open position",
    ["ticker", "direction"],
)

PAPER_EQUITY = Gauge(
    "paper_equity_usd",
    "Current paper trading net liquidation value (USD)",
)

DAILY_PNL_PCT = Gauge(
    "daily_pnl_pct",
    "Daily P&L as a fraction of NLV",
)

DRAWDOWN = Gauge(
    "drawdown_from_hwm",
    "Current drawdown from the all-time high-water mark (fraction)",
)

OPEN_POSITIONS_COUNT = Gauge(
    "open_positions_count",
    "Number of currently open positions",
)

# ── Circuit breaker state constants ──────────────────────────────────────────

CIRCUIT_STATE_VALUES = {
    "NORMAL": 0,
    "REDUCED_50": 1,
    "DAILY_HALT": 2,
    "FULL_HALT": 3,
}


# ── Helpers ───────────────────────────────────────────────────────────────────

def start_metrics_server(port: int = 8000) -> None:
    """
    Start the Prometheus HTTP metrics server on the given port.
    Call once at service startup, before entering the main loop.
    Idempotent — logs a warning and continues if the port is already bound.
    """
    try:
        start_http_server(port)
        logger.info("Prometheus metrics server started on :%d/metrics", port)
    except OSError as exc:
        logger.warning("Could not start metrics server on port %d: %s", port, exc)


def set_circuit_breaker_state(state_name: str) -> None:
    """Update CIRCUIT_BREAKER_STATE gauge from a state name string."""
    value = CIRCUIT_STATE_VALUES.get(state_name, 0)
    CIRCUIT_BREAKER_STATE.set(value)
